/*
# CRIMEWATCH — Core Schema

Creates the complete database schema for the CRIMEWATCH crime & safety intelligence platform.

## Tables Created

1. **profiles** — Extends auth.users with a role (ADMIN/ANALYST/VIEWER), display name, and avatar URL.
2. **crime_categories** — Reference table of crime categories with severity weighting.
3. **locations** — Named geographic areas (districts) used for analytics.
4. **crime_incidents** — Core fact table: 10,000+ synthetic demo rows.
5. **hotspots** — Computed geographic clusters with risk scores.
6. **risk_scores** — Per-location aggregate risk scores with contributors.
7. **reports** — Saved report metadata generated by users.
8. **notifications** — User-facing notification feed.

## Security

- RLS enabled on every table.
- profiles: readable by all authenticated, updatable by owner.
- crime_incidents / crime_categories / locations / hotspots / risk_scores: readable by all authenticated; writes restricted to ADMIN and ANALYST via helper functions.
- reports / notifications: owner-scoped.
- SECURITY DEFINER functions is_admin() and is_analyst_or_admin() provided for policy predicates.

## Demo Data

- Seeds all crime_categories.
- Seeds 8 fictional locations.
- Seeds 10,000 synthetic crime_incidents with realistic clustering.
- Seeds hotspots and risk_scores per location.

## Notes

1. All synthetic data is labeled via is_synthetic boolean.
2. Indexes on all commonly-filtered columns.
3. Helper functions created AFTER profiles table to avoid forward-reference errors.
*/

-- ============================================================
-- PROFILES (created first so helper functions can reference it)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text,
  role text NOT NULL DEFAULT 'VIEWER' CHECK (role IN ('ADMIN', 'ANALYST', 'VIEWER')),
  avatar_url text,
  theme text NOT NULL DEFAULT 'dark',
  notification_prefs jsonb NOT NULL DEFAULT '{"email": true, "in_app": true, "risk_alerts": true}'::jsonb,
  data_prefs jsonb NOT NULL DEFAULT '{"default_date_range": "30d", "synthetic_label": true}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_all" ON public.profiles;
CREATE POLICY "profiles_select_all" ON public.profiles
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

-- ============================================================
-- HELPER FUNCTIONS (after profiles table exists)
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'ADMIN'
  );
$$;

CREATE OR REPLACE FUNCTION public.is_analyst_or_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role IN ('ADMIN', 'ANALYST')
  );
$$;

-- ============================================================
-- CRIME CATEGORIES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.crime_categories (
  id serial PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  base_severity text NOT NULL DEFAULT 'Medium' CHECK (base_severity IN ('Low','Medium','High','Critical')),
  severity_weight numeric NOT NULL DEFAULT 2.0 CHECK (severity_weight >= 0 AND severity_weight <= 4)
);

ALTER TABLE public.crime_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categories_select" ON public.crime_categories;
CREATE POLICY "categories_select" ON public.crime_categories
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "categories_insert_admin" ON public.crime_categories;
CREATE POLICY "categories_insert_admin" ON public.crime_categories
  FOR INSERT TO authenticated WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "categories_update_admin" ON public.crime_categories;
CREATE POLICY "categories_update_admin" ON public.crime_categories
  FOR UPDATE TO authenticated USING (public.is_analyst_or_admin()) WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "categories_delete_admin" ON public.crime_categories;
CREATE POLICY "categories_delete_admin" ON public.crime_categories
  FOR DELETE TO authenticated USING (public.is_analyst_or_admin());

-- ============================================================
-- LOCATIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.locations (
  id serial PRIMARY KEY,
  name text NOT NULL UNIQUE,
  district text,
  city text NOT NULL DEFAULT 'Metro City',
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  radius_km numeric NOT NULL DEFAULT 2.0,
  population integer,
  area_km2 numeric
);

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "locations_select" ON public.locations;
CREATE POLICY "locations_select" ON public.locations
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "locations_insert_admin" ON public.locations;
CREATE POLICY "locations_insert_admin" ON public.locations
  FOR INSERT TO authenticated WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "locations_update_admin" ON public.locations;
CREATE POLICY "locations_update_admin" ON public.locations
  FOR UPDATE TO authenticated USING (public.is_analyst_or_admin()) WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "locations_delete_admin" ON public.locations;
CREATE POLICY "locations_delete_admin" ON public.locations
  FOR DELETE TO authenticated USING (public.is_analyst_or_admin());

-- ============================================================
-- CRIME INCIDENTS (core fact table)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.crime_incidents (
  id serial PRIMARY KEY,
  incident_id text NOT NULL UNIQUE,
  date date NOT NULL,
  time text,
  crime_type text NOT NULL,
  category text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('Low','Medium','High','Critical')),
  location text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  status text NOT NULL DEFAULT 'Open' CHECK (status IN ('Open','Under Investigation','Closed','Arrested')),
  is_synthetic boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.crime_incidents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "incidents_select" ON public.crime_incidents;
CREATE POLICY "incidents_select" ON public.crime_incidents
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "incidents_insert_admin" ON public.crime_incidents;
CREATE POLICY "incidents_insert_admin" ON public.crime_incidents
  FOR INSERT TO authenticated WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "incidents_update_admin" ON public.crime_incidents;
CREATE POLICY "incidents_update_admin" ON public.crime_incidents
  FOR UPDATE TO authenticated USING (public.is_analyst_or_admin()) WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "incidents_delete_admin" ON public.crime_incidents;
CREATE POLICY "incidents_delete_admin" ON public.crime_incidents
  FOR DELETE TO authenticated USING (public.is_analyst_or_admin());

CREATE INDEX IF NOT EXISTS idx_incidents_date ON public.crime_incidents(date);
CREATE INDEX IF NOT EXISTS idx_incidents_crime_type ON public.crime_incidents(crime_type);
CREATE INDEX IF NOT EXISTS idx_incidents_category ON public.crime_incidents(category);
CREATE INDEX IF NOT EXISTS idx_incidents_severity ON public.crime_incidents(severity);
CREATE INDEX IF NOT EXISTS idx_incidents_location ON public.crime_incidents(location);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON public.crime_incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_lat_lng ON public.crime_incidents(latitude, longitude);

-- ============================================================
-- HOTSPOTS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.hotspots (
  id serial PRIMARY KEY,
  hotspot_id text NOT NULL UNIQUE,
  name text NOT NULL,
  location text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  radius_km numeric NOT NULL DEFAULT 0.5,
  incident_count integer NOT NULL DEFAULT 0,
  dominant_crime text,
  avg_severity numeric,
  peak_time text,
  risk_score numeric NOT NULL DEFAULT 0 CHECK (risk_score >= 0 AND risk_score <= 100),
  risk_level text NOT NULL DEFAULT 'LOW' CHECK (risk_level IN ('VERY LOW','LOW','MODERATE','HIGH','CRITICAL')),
  method text NOT NULL DEFAULT 'DBSCAN',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.hotspots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hotspots_select" ON public.hotspots;
CREATE POLICY "hotspots_select" ON public.hotspots
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "hotspots_insert_admin" ON public.hotspots;
CREATE POLICY "hotspots_insert_admin" ON public.hotspots
  FOR INSERT TO authenticated WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "hotspots_update_admin" ON public.hotspots;
CREATE POLICY "hotspots_update_admin" ON public.hotspots
  FOR UPDATE TO authenticated USING (public.is_analyst_or_admin()) WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "hotspots_delete_admin" ON public.hotspots;
CREATE POLICY "hotspots_delete_admin" ON public.hotspots
  FOR DELETE TO authenticated USING (public.is_analyst_or_admin());

-- ============================================================
-- RISK SCORES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.risk_scores (
  id serial PRIMARY KEY,
  location text NOT NULL,
  period text NOT NULL DEFAULT 'overall',
  risk_score numeric NOT NULL DEFAULT 0 CHECK (risk_score >= 0 AND risk_score <= 100),
  risk_level text NOT NULL DEFAULT 'LOW' CHECK (risk_level IN ('VERY LOW','LOW','MODERATE','HIGH','CRITICAL')),
  trend text NOT NULL DEFAULT 'stable' CHECK (trend IN ('increasing','decreasing','stable')),
  contributors jsonb NOT NULL DEFAULT '[]'::jsonb,
  frequency_component numeric,
  severity_component numeric,
  recency_component numeric,
  hotspot_component numeric,
  temporal_component numeric,
  trend_component numeric,
  calculated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.risk_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "risk_select" ON public.risk_scores;
CREATE POLICY "risk_select" ON public.risk_scores
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "risk_insert_admin" ON public.risk_scores;
CREATE POLICY "risk_insert_admin" ON public.risk_scores
  FOR INSERT TO authenticated WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "risk_update_admin" ON public.risk_scores;
CREATE POLICY "risk_update_admin" ON public.risk_scores
  FOR UPDATE TO authenticated USING (public.is_analyst_or_admin()) WITH CHECK (public.is_analyst_or_admin());

DROP POLICY IF EXISTS "risk_delete_admin" ON public.risk_scores;
CREATE POLICY "risk_delete_admin" ON public.risk_scores
  FOR DELETE TO authenticated USING (public.is_analyst_or_admin());

-- ============================================================
-- REPORTS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  report_type text NOT NULL,
  date_range_start date,
  date_range_end date,
  summary jsonb,
  status text NOT NULL DEFAULT 'generated' CHECK (status IN ('generated','draft','archived')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reports_select_own" ON public.reports;
CREATE POLICY "reports_select_own" ON public.reports
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "reports_insert_own" ON public.reports;
CREATE POLICY "reports_insert_own" ON public.reports
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "reports_update_own" ON public.reports;
CREATE POLICY "reports_update_own" ON public.reports
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "reports_delete_own" ON public.reports;
CREATE POLICY "reports_delete_own" ON public.reports
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info' CHECK (type IN ('info','warning','danger','success')),
  read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_select_own" ON public.notifications;
CREATE POLICY "notifications_select_own" ON public.notifications
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "notifications_insert_own" ON public.notifications;
CREATE POLICY "notifications_insert_own" ON public.notifications
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "notifications_update_own" ON public.notifications;
CREATE POLICY "notifications_update_own" ON public.notifications
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "notifications_delete_own" ON public.notifications;
CREATE POLICY "notifications_delete_own" ON public.notifications
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ============================================================
-- TRIGGER: auto-create profile on signup
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'role', 'VIEWER')
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- SEED: CRIME CATEGORIES
-- ============================================================

INSERT INTO public.crime_categories (name, description, base_severity, severity_weight) VALUES
  ('Theft', 'Property theft including pickpocketing and shoplifting', 'Low', 1.5),
  ('Assault', 'Physical assault and battery', 'High', 3.0),
  ('Burglary', 'Unlawful entry into a building to commit theft', 'High', 2.8),
  ('Robbery', 'Taking property by force or threat', 'High', 3.2),
  ('Fraud', 'Financial fraud and deception', 'Medium', 2.0),
  ('Vandalism', 'Property damage and graffiti', 'Low', 1.2),
  ('Drug-related', 'Drug possession, trafficking, and related offenses', 'Medium', 2.5),
  ('Vehicle Crime', 'Vehicle theft and break-ins', 'Medium', 2.2),
  ('Cybercrime', 'Online fraud, hacking, and digital crimes', 'Medium', 2.3),
  ('Other', 'Miscellaneous criminal incidents', 'Low', 1.5)
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- SEED: LOCATIONS
-- ============================================================

INSERT INTO public.locations (name, district, latitude, longitude, radius_km, population, area_km2) VALUES
  ('Downtown District', 'Central', 40.7589, -73.9851, 2.0, 85000, 12.5),
  ('Riverside', 'East', 40.7420, -73.9600, 2.5, 62000, 15.0),
  ('Midtown North', 'Central', 40.7700, -73.9850, 1.8, 78000, 10.2),
  ('Harborfront', 'South', 40.7200, -74.0100, 3.0, 45000, 18.0),
  ('Eastgate', 'East', 40.7800, -73.9400, 2.2, 53000, 14.0),
  ('Westside Park', 'West', 40.7680, -74.0200, 2.0, 60000, 11.5),
  ('Northpoint', 'North', 40.8100, -73.9700, 2.5, 41000, 16.0),
  ('Industrial Zone', 'Southwest', 40.7300, -74.0400, 3.5, 18000, 22.0)
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- SEED: CRIME INCIDENTS (10,000 synthetic records)
-- ============================================================

INSERT INTO public.crime_incidents (incident_id, date, time, crime_type, category, severity, location, latitude, longitude, status, is_synthetic)
SELECT
  'INC-' || lpad(g::text, 6, '0'),
  (DATE '2024-01-01' + (random() * 670)::int) AS date,
  lpad(( (random() * 23)::int)::text, 2, '0') || ':' || lpad(( (random() * 59)::int)::text, 2, '0') AS time,
  ct.crime_type,
  ct.crime_type AS category,
  ct.severity,
  loc.loc_name,
  loc.loc_lat + (random() - 0.5) * 0.03,
  loc.loc_lng + (random() - 0.5) * 0.03,
  CASE WHEN random() < 0.25 THEN 'Closed' WHEN random() < 0.45 THEN 'Under Investigation' WHEN random() < 0.52 THEN 'Arrested' ELSE 'Open' END,
  true
FROM generate_series(1, 10000) AS g
CROSS JOIN LATERAL (
  SELECT
    CASE
      WHEN random() < 0.22 THEN 'Theft'
      WHEN random() < 0.38 THEN 'Assault'
      WHEN random() < 0.50 THEN 'Burglary'
      WHEN random() < 0.62 THEN 'Robbery'
      WHEN random() < 0.72 THEN 'Fraud'
      WHEN random() < 0.80 THEN 'Vandalism'
      WHEN random() < 0.87 THEN 'Drug-related'
      WHEN random() < 0.93 THEN 'Vehicle Crime'
      WHEN random() < 0.98 THEN 'Cybercrime'
      ELSE 'Other'
    END AS crime_type,
    CASE
      WHEN random() < 0.35 THEN 'Low'
      WHEN random() < 0.70 THEN 'Medium'
      WHEN random() < 0.90 THEN 'High'
      ELSE 'Critical'
    END AS severity
) AS ct
CROSS JOIN LATERAL (
  SELECT
    CASE
      WHEN random() < 0.28 THEN 'Downtown District'
      WHEN random() < 0.45 THEN 'Riverside'
      WHEN random() < 0.58 THEN 'Midtown North'
      WHEN random() < 0.70 THEN 'Harborfront'
      WHEN random() < 0.80 THEN 'Eastgate'
      WHEN random() < 0.88 THEN 'Westside Park'
      WHEN random() < 0.95 THEN 'Northpoint'
      ELSE 'Industrial Zone'
    END AS loc_name,
    CASE
      WHEN random() < 0.28 THEN 40.7589
      WHEN random() < 0.45 THEN 40.7420
      WHEN random() < 0.58 THEN 40.7700
      WHEN random() < 0.70 THEN 40.7200
      WHEN random() < 0.80 THEN 40.7800
      WHEN random() < 0.88 THEN 40.7680
      WHEN random() < 0.95 THEN 40.8100
      ELSE 40.7300
    END AS loc_lat,
    CASE
      WHEN random() < 0.28 THEN -73.9851
      WHEN random() < 0.45 THEN -73.9600
      WHEN random() < 0.58 THEN -73.9850
      WHEN random() < 0.70 THEN -74.0100
      WHEN random() < 0.80 THEN -73.9400
      WHEN random() < 0.88 THEN -74.0200
      WHEN random() < 0.95 THEN -73.9700
      ELSE -74.0400
    END AS loc_lng
) AS loc;
